services:
  - type: web
    name: word-to-pdf-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    region: oregon
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production
